-- لعبة ارسم واتقال: شغّل الملف كاملًا في Supabase SQL Editor بعد مخطط الموقع الحالي.
-- تعتمد اللعبة على service_role في route handlers، لذلك لا نكشف أي مفتاح سري في المتصفح.

create table if not exists pictionary_rooms (
  id uuid primary key default gen_random_uuid(),
  code text not null unique,
  name text not null default 'غرفة الأصحاب',
  status text not null default 'waiting' check (status in ('waiting', 'drawing', 'round_end', 'finished')),
  round_number integer not null default 1,
  max_rounds integer not null default 5,
  current_drawer_id uuid references users(id) on delete set null,
  current_word text,
  word_options jsonb not null default '[]'::jsonb,
  round_started_at timestamptz,
  round_ends_at timestamptz,
  created_by uuid references users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table pictionary_rooms add column if not exists max_players integer not null default 6;

create table if not exists pictionary_room_players (
  room_id uuid not null references pictionary_rooms(id) on delete cascade,
  user_id uuid not null references users(id) on delete cascade,
  score integer not null default 0,
  round_coins integer not null default 0,
  is_connected boolean not null default true,
  is_ready boolean not null default false,
  joined_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  primary key (room_id, user_id)
);

create table if not exists pictionary_rounds (
  id uuid primary key default gen_random_uuid(),
  room_id uuid not null references pictionary_rooms(id) on delete cascade,
  round_number integer not null,
  drawer_id uuid not null references users(id) on delete cascade,
  chosen_word text not null,
  status text not null default 'drawing' check (status in ('drawing', 'round_end', 'finished')),
  started_at timestamptz not null default now(),
  ends_at timestamptz not null,
  winner_id uuid references users(id) on delete set null,
  winner_points integer not null default 0,
  winner_coins integer not null default 0,
  created_at timestamptz not null default now(),
  unique (room_id, round_number)
);

create table if not exists pictionary_strokes (
  id bigint generated by default as identity primary key,
  room_id uuid not null references pictionary_rooms(id) on delete cascade,
  round_id uuid not null references pictionary_rounds(id) on delete cascade,
  user_id uuid not null references users(id) on delete cascade,
  points jsonb not null,
  color text not null default '#f5b942',
  brush_size integer not null default 8,
  tool text not null default 'brush' check (tool in ('brush', 'eraser')),
  created_at timestamptz not null default now()
);

alter table pictionary_strokes add column if not exists tool text not null default 'brush';

create table if not exists pictionary_messages (
  id bigint generated by default as identity primary key,
  room_id uuid not null references pictionary_rooms(id) on delete cascade,
  round_id uuid references pictionary_rounds(id) on delete set null,
  user_id uuid references users(id) on delete set null,
  body text not null check (char_length(body) between 1 and 120),
  is_guess boolean not null default true,
  is_correct boolean not null default false,
  created_at timestamptz not null default now()
);

-- بنك كلمات «ارسم واتقال»: يديره الأدمن، وتختار اللعبة منه 3 كلمات عشوائية لكل جولة.
create table if not exists pictionary_word_bank (
  id uuid primary key default gen_random_uuid(),
  word text not null check (char_length(trim(word)) between 2 and 48),
  normalized_word text not null unique check (char_length(normalized_word) between 2 and 48),
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

insert into pictionary_word_bank (word, normalized_word) values
  ('مظلة', 'مظلة'),
  ('صاروخ', 'صاروخ'),
  ('بيتزا', 'بيتزا')
on conflict (normalized_word) do nothing;

create index if not exists idx_pictionary_rooms_updated on pictionary_rooms(updated_at desc);
create index if not exists idx_pictionary_players_room on pictionary_room_players(room_id, score desc);
create index if not exists idx_pictionary_rounds_room on pictionary_rounds(room_id, round_number desc);
create index if not exists idx_pictionary_strokes_round on pictionary_strokes(round_id, created_at);
create index if not exists idx_pictionary_messages_room on pictionary_messages(room_id, created_at desc);
create index if not exists idx_pictionary_word_bank_active on pictionary_word_bank(is_active, created_at desc);

-- تحديث updated_at عند تعديل حالة الغرفة من route handlers.
create or replace function touch_pictionary_room_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_touch_pictionary_room on pictionary_rooms;
create trigger trg_touch_pictionary_room
before update on pictionary_rooms
for each row execute function touch_pictionary_room_updated_at();

-- الـ route handlers تستخدم service_role ولا تسمح بقراءة الجداول مباشرة من العميل.
alter table pictionary_rooms enable row level security;
alter table pictionary_room_players enable row level security;
alter table pictionary_rounds enable row level security;
alter table pictionary_strokes enable row level security;
alter table pictionary_messages enable row level security;
alter table pictionary_word_bank enable row level security;
