-- مافيوسو أونلاين: شغّل الملف كاملًا في Supabase SQL Editor بعد مخطط الموقع الحالي.
-- كل القراءة والكتابة تمر من Route Handlers باستخدام service_role؛ لا تُكشف الأدوار للمتصفح مباشرة.

create table if not exists mafioso_cases (
  id uuid primary key default gen_random_uuid(),
  title text not null check (char_length(trim(title)) between 3 and 90),
  subtitle text not null default '',
  briefing text not null default '',
  reveal_title text not null default 'الحقيقة الكاملة',
  reveal_story text not null default '',
  reveal_audio_path text,
  is_active boolean not null default true,
  created_by uuid references users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists mafioso_case_roles (
  id uuid primary key default gen_random_uuid(),
  case_id uuid not null references mafioso_cases(id) on delete cascade,
  role_name text not null check (char_length(trim(role_name)) between 2 and 60),
  public_motive text not null default '',
  private_card_text text not null default '',
  alignment text not null check (alignment in ('mafia', 'innocent')),
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  unique(case_id, role_name)
);

create table if not exists mafioso_case_clues (
  id uuid primary key default gen_random_uuid(),
  case_id uuid not null references mafioso_cases(id) on delete cascade,
  round_number integer not null check (round_number between 1 and 4),
  clue_text text not null check (char_length(trim(clue_text)) between 4 and 500),
  created_at timestamptz not null default now(),
  unique(case_id, round_number)
);

create table if not exists mafioso_rooms (
  id uuid primary key default gen_random_uuid(),
  code text not null unique check (char_length(code) between 4 and 10),
  name text not null default 'غرفة القضية',
  case_id uuid references mafioso_cases(id) on delete set null,
  status text not null default 'waiting' check (status in ('waiting', 'role_reveal', 'boss_intro', 'clue_reveal', 'discussion', 'vote_announcement', 'voting', 'vote_result', 'finished')),
  round_number integer not null default 1 check (round_number between 1 and 5),
  phase_ends_at timestamptz,
  current_clue_id uuid references mafioso_case_clues(id) on delete set null,
  final_winner text check (final_winner in ('mafia', 'innocent')),
  last_eliminated_user_id uuid references users(id) on delete set null,
  last_eliminated_alignment text check (last_eliminated_alignment in ('mafia', 'innocent')),
  created_by uuid references users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists mafioso_room_players (
  room_id uuid not null references mafioso_rooms(id) on delete cascade,
  user_id uuid not null references users(id) on delete cascade,
  role_id uuid references mafioso_case_roles(id) on delete set null,
  alignment text check (alignment in ('mafia', 'innocent')),
  status text not null default 'active' check (status in ('active', 'eliminated', 'left')),
  is_connected boolean not null default true,
  role_acknowledged_at timestamptz,
  joined_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  primary key (room_id, user_id)
);

create table if not exists mafioso_messages (
  id bigint generated by default as identity primary key,
  room_id uuid not null references mafioso_rooms(id) on delete cascade,
  round_number integer not null check (round_number between 1 and 5),
  user_id uuid references users(id) on delete set null,
  body text not null check (char_length(trim(body)) between 1 and 420),
  created_at timestamptz not null default now()
);

create table if not exists mafioso_votes (
  id bigint generated by default as identity primary key,
  room_id uuid not null references mafioso_rooms(id) on delete cascade,
  round_number integer not null check (round_number between 1 and 5),
  voter_id uuid not null references users(id) on delete cascade,
  target_id uuid not null references users(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique(room_id, round_number, voter_id)
);

-- لو كنت شغّلت نسخة سابقة من SQL كانت تسمح بأربع جولات فقط، حدّث القيود لتسمح بجولة الحسم الخامسة.
alter table mafioso_rooms drop constraint if exists mafioso_rooms_round_number_check;
alter table mafioso_rooms add constraint mafioso_rooms_round_number_check check (round_number between 1 and 5);
alter table mafioso_rooms add column if not exists last_eliminated_user_id uuid references users(id) on delete set null;
alter table mafioso_rooms add column if not exists last_eliminated_alignment text check (last_eliminated_alignment in ('mafia', 'innocent'));
alter table mafioso_rooms drop constraint if exists mafioso_rooms_status_check;
alter table mafioso_rooms add constraint mafioso_rooms_status_check check (status in ('waiting', 'role_reveal', 'boss_intro', 'clue_reveal', 'discussion', 'vote_announcement', 'voting', 'vote_result', 'finished'));
alter table mafioso_messages drop constraint if exists mafioso_messages_round_number_check;
alter table mafioso_messages add constraint mafioso_messages_round_number_check check (round_number between 1 and 5);
alter table mafioso_votes drop constraint if exists mafioso_votes_round_number_check;
alter table mafioso_votes add constraint mafioso_votes_round_number_check check (round_number between 1 and 5);

create index if not exists idx_mafioso_cases_active on mafioso_cases(is_active, created_at desc);
create index if not exists idx_mafioso_roles_case on mafioso_case_roles(case_id, sort_order);
create index if not exists idx_mafioso_clues_case on mafioso_case_clues(case_id, round_number);
create index if not exists idx_mafioso_rooms_updated on mafioso_rooms(updated_at desc);
create index if not exists idx_mafioso_players_room on mafioso_room_players(room_id, status);
create index if not exists idx_mafioso_messages_room on mafioso_messages(room_id, created_at desc);
create index if not exists idx_mafioso_votes_room_round on mafioso_votes(room_id, round_number);

create or replace function touch_mafioso_room_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_touch_mafioso_room on mafioso_rooms;
create trigger trg_touch_mafioso_room
before update on mafioso_rooms
for each row execute function touch_mafioso_room_updated_at();

create or replace function touch_mafioso_case_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_touch_mafioso_case on mafioso_cases;
create trigger trg_touch_mafioso_case
before update on mafioso_cases
for each row execute function touch_mafioso_case_updated_at();

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('mafioso-media', 'mafioso-media', true, 5242880, array['audio/mpeg', 'audio/wav', 'audio/x-wav', 'audio/mp4', 'audio/ogg'])
on conflict (id) do update set public = true, file_size_limit = 5242880;

-- قضية تجريبية: يمكن حذفها بالكامل من تبويب مافيوسو في الأدمن بعد إضافة قضيتك الخاصة.
insert into mafioso_cases (id, title, subtitle, briefing, reveal_title, reveal_story, is_active)
values (
  '10000000-0000-4000-8000-000000000001',
  'سرّ المفتاح الذهبي',
  'اختفى مفتاح شقة الدور السابع قبل دقائق من وصول صاحبته.',
  'كل واحد في العمارة كان عنده سبب يراقب المفتاح. اسمعوا الدوافع كويس، وبعد كل دليل ناقشوا مين قصته مش راكبة.',
  'الحقيقة وراء المفتاح الذهبي',
  'البواب وعامل الصيانة اتفقوا على سرقة المفتاح ليدخلوا الشقة بعد أن تأكدوا أن صاحبتها خارج البيت. المندوب لم يرَ سوى عامل الصيانة وهو يخفي نسخة قديمة من المفتاح، والجارة كانت تتحدث كثيرًا لأنها سمعت الشجار من السلم.',
  true
)
on conflict (id) do nothing;

insert into mafioso_case_roles (case_id, role_name, public_motive, private_card_text, alignment, sort_order) values
  ('10000000-0000-4000-8000-000000000001', 'البواب محمود', 'كان غاضبًا لأن صاحبة الشقة اشتكت منه للإدارة أكثر من مرة.', 'أنت من المافيا. اتفقت مع عامل الصيانة على الوصول للمفتاح، واخترع قصة تقنع الباقي أن المندوب هو المشتبه.', 'mafia', 1),
  ('10000000-0000-4000-8000-000000000001', 'عامل الصيانة رامي', 'كان يدخل العمارة كثيرًا بحجة إصلاح أعطال السباكة.', 'أنت من المافيا. ساعدت البواب في أخذ المفتاح. لا تكشف إنك كنت قرب صندوق الكهرباء وقت السرقة.', 'mafia', 2),
  ('10000000-0000-4000-8000-000000000001', 'الجارة فوزية', 'كانت تعرف تفاصيل العمارة كلها وتحب الكلام عن الجيران.', 'أنت بريء. سمعت صوت شجار عند السلم، لكنك لم تشاهدي من أخذ المفتاح.', 'innocent', 3),
  ('10000000-0000-4000-8000-000000000001', 'مندوب التوصيل سامي', 'وصل لطلب أمام العمارة في وقت قريب من اختفاء المفتاح.', 'أنت بريء. رأيت عامل الصيانة قرب صندوق الكهرباء، لكنك لا تعرف لماذا كان هناك.', 'innocent', 4),
  ('10000000-0000-4000-8000-000000000001', 'ابن صاحبة الشقة كريم', 'كان يريد دخول الشقة قبل عودة والدته ليدعو أصدقاءه.', 'أنت بريء. كنت غاضبًا لأنك نسيت مفتاحك، لكنك لم تلمس المفتاح الذهبي.', 'innocent', 5)
on conflict (case_id, role_name) do nothing;

insert into mafioso_case_clues (case_id, round_number, clue_text) values
  ('10000000-0000-4000-8000-000000000001', 1, 'وجد مافيا بوص أثر زيت خفيف على نسخة المفتاح، وهو نفس الزيت المستخدم في أدوات الصيانة.'),
  ('10000000-0000-4000-8000-000000000001', 2, 'كاميرا المصعد تعطلت قبل السرقة بدقائق، لكن سجّل الصيانة لم يكن يحتوي بلاغًا جديدًا.'),
  ('10000000-0000-4000-8000-000000000001', 3, 'الجارة سمعت صوت شخصين يتجادلان عن موعد عودة صاحبة الشقة.'),
  ('10000000-0000-4000-8000-000000000001', 4, 'وجدت قصاصة ورق قرب الاستقبال عليها رقم الشقة السابع وخط يد البواب.')
on conflict (case_id, round_number) do nothing;

alter table mafioso_cases enable row level security;
alter table mafioso_case_roles enable row level security;
alter table mafioso_case_clues enable row level security;
alter table mafioso_rooms enable row level security;
alter table mafioso_room_players enable row level security;
alter table mafioso_messages enable row level security;
alter table mafioso_votes enable row level security;
