// Style reminder: Admin Mafioso tools are an orderly case file—highly legible forms, a clear 2-vs-3 role balance, and no ambiguity about what becomes public or secret.
"use client";

import { useEffect, useMemo, useState } from "react";
import ShakeButton from "./ShakeButton";

type Role = { id?: string; role_name: string; public_motive: string; private_card_text: string; alignment: "mafia" | "innocent"; sort_order?: number };
type Case = { id: string; title: string; subtitle: string; briefing: string; reveal_title: string; reveal_story: string; reveal_audio_path: string | null; is_active: boolean; roles: Role[]; clues: Array<{ id?: string; round_number: number; clue_text: string }> };
const defaultRoles = (): Role[] => Array.from({ length: 5 }, (_, index) => ({ role_name: "", public_motive: "", private_card_text: "", alignment: index < 2 ? "mafia" : "innocent" }));
const defaultClues = () => Array.from({ length: 4 }, (_, index) => ({ round_number: index + 1, clue_text: "" }));

export default function MafiosoCaseManager() {
  const [cases, setCases] = useState<Case[]>([]); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [success, setSuccess] = useState("");
  const [editingId, setEditingId] = useState<string | null>(null); const [title, setTitle] = useState(""); const [subtitle, setSubtitle] = useState(""); const [briefing, setBriefing] = useState(""); const [revealTitle, setRevealTitle] = useState("الحقيقة الكاملة"); const [revealStory, setRevealStory] = useState(""); const [isActive, setIsActive] = useState(true); const [roles, setRoles] = useState<Role[]>(defaultRoles); const [clues, setClues] = useState(defaultClues); const [revealAudio, setRevealAudio] = useState<File | null>(null); const [removeReveal, setRemoveReveal] = useState(false); const [fileKey, setFileKey] = useState(0);
  const mafiaCount = useMemo(() => roles.filter((role) => role.alignment === "mafia").length, [roles]);
  async function load() { setLoading(true); const res = await fetch("/api/admin/mafioso-cases", { cache: "no-store" }); const data = await res.json().catch(() => ({})); setCases(data.cases || []); setError(res.ok ? "" : data.error || "حصل خطأ أثناء تحميل القضايا"); setLoading(false); }
  useEffect(() => { void load(); }, []);
  function resetForm() { setEditingId(null); setTitle(""); setSubtitle(""); setBriefing(""); setRevealTitle("الحقيقة الكاملة"); setRevealStory(""); setIsActive(true); setRoles(defaultRoles()); setClues(defaultClues()); setRevealAudio(null); setRemoveReveal(false); setFileKey((value) => value + 1); setError(""); }
  function edit(caseRow: Case) { setEditingId(caseRow.id); setTitle(caseRow.title); setSubtitle(caseRow.subtitle || ""); setBriefing(caseRow.briefing || ""); setRevealTitle(caseRow.reveal_title || "الحقيقة الكاملة"); setRevealStory(caseRow.reveal_story || ""); setIsActive(caseRow.is_active); setRoles([...caseRow.roles].sort((a,b) => (a.sort_order || 0) - (b.sort_order || 0)).map(({ role_name, public_motive, private_card_text, alignment }) => ({ role_name, public_motive, private_card_text, alignment }))); setClues([...caseRow.clues].sort((a,b) => a.round_number - b.round_number).map((clue) => ({ round_number: clue.round_number, clue_text: clue.clue_text }))); setRevealAudio(null); setRemoveReveal(false); setFileKey((value) => value + 1); setError(""); window.scrollTo({ top: 0, behavior: "smooth" }); }
  function updateRole(index: number, field: keyof Role, value: string) { setRoles((current) => current.map((role, roleIndex) => roleIndex === index ? { ...role, [field]: value } : role)); }
  function updateClue(index: number, value: string) { setClues((current) => current.map((clue, clueIndex) => clueIndex === index ? { ...clue, clue_text: value } : clue)); }
  async function save() {
    setError(""); setSuccess("");
    if (!title.trim() || !briefing.trim() || !revealTitle.trim() || !revealStory.trim() || mafiaCount !== 2 || roles.some((role) => !role.role_name.trim() || !role.public_motive.trim() || !role.private_card_text.trim()) || clues.some((clue) => clue.clue_text.trim().length < 4)) { setError("اكتب كل البيانات: 5 شخصيات بالظبط منهم 2 مافيوسو، و4 أدلة، وقصة النهاية."); return; }
    setBusy(true); const form = new FormData(); form.append("title", title); form.append("subtitle", subtitle); form.append("briefing", briefing); form.append("revealTitle", revealTitle); form.append("revealStory", revealStory); form.append("isActive", String(isActive)); form.append("roles", JSON.stringify(roles.map((role) => ({ roleName: role.role_name, publicMotive: role.public_motive, privateCardText: role.private_card_text, alignment: role.alignment })))); form.append("clues", JSON.stringify(clues.map((clue) => clue.clue_text))); form.append("removeReveal", String(removeReveal && !revealAudio)); if (revealAudio) form.append("revealAudio", revealAudio); if (editingId) form.append("caseId", editingId);
    const res = await fetch("/api/admin/mafioso-cases", { method: editingId ? "PATCH" : "POST", body: form }); const data = await res.json().catch(() => ({})); setBusy(false); if (!res.ok) { setError(data.error || "حصل خطأ أثناء الحفظ"); return; } setSuccess(editingId ? "اتحفظ تعديل القضية" : "اتضافت القضية وبقت جاهزة للرومات"); resetForm(); await load();
  }
  async function remove(caseRow: Case) { if (!window.confirm(`متأكد إنك عايز تحذف قضية «${caseRow.title}»؟`)) return; setBusy(true); setError(""); const res = await fetch("/api/admin/mafioso-cases", { method: "DELETE", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ caseId: caseRow.id }) }); const data = await res.json().catch(() => ({})); setBusy(false); if (!res.ok) { setError(data.error || "تعذر حذف القضية"); return; } if (editingId === caseRow.id) resetForm(); await load(); }
  return <>
    <div className="card mafioso-admin-card" style={{ marginBottom: 22 }}>
      <span className="song-eyebrow">ملف قضية جديد</span><h3 style={{ marginTop: 7 }}>{editingId ? "✎ تعديل قضية مافيوسو" : "أضف قضية مافيوسو"}</h3><p className="muted" style={{ fontSize: 13, marginTop: 0 }}>كل روم تسحب قضية مفعلة عشوائيًا. اللاعبين يرون الدوافع العامة فقط؛ الكارت السري يراه صاحبه وحده.</p>
      {error && <div className="error-text">{error}</div>}{success && <div className="success-text">{success}</div>}
      <div className="field"><label>عنوان القضية</label><input className="input" value={title} maxLength={90} placeholder="مثال: سرّ المفتاح الذهبي" onChange={(event) => setTitle(event.target.value)} /></div>
      <div className="field"><label>وصف قصير يظهر في بداية اللعبة</label><input className="input" value={subtitle} maxLength={300} placeholder="مثال: اختفى مفتاح شقة الدور السابع" onChange={(event) => setSubtitle(event.target.value)} /></div>
      <div className="field"><label>رسالة مافيا بوص قبل الأدلة</label><textarea className="input song-admin-textarea" value={briefing} maxLength={1200} placeholder="اشرح جو القضية وما على اللاعبين ملاحظته." onChange={(event) => setBriefing(event.target.value)} /></div>
      <div className="mafioso-admin-section"><div><h4>الشخصيات السرية</h4><p>اللازم 5 شخصيات: <b className={mafiaCount === 2 ? "mafioso-admin-good" : "mafioso-admin-bad"}>{mafiaCount}/2 مافيوسو</b> و3 بريئين.</p></div>{roles.map((role, index) => <div className="mafioso-admin-role" key={index}><div className="field"><label>الشخصية {index + 1}</label><input className="input" maxLength={60} value={role.role_name} placeholder="مثال: البواب محمود" onChange={(event) => updateRole(index, "role_name", event.target.value)} /></div><div className="field"><label>نوع الدور</label><select className="input" value={role.alignment} onChange={(event) => updateRole(index, "alignment", event.target.value)}><option value="mafia">مافيوسو</option><option value="innocent">بريء</option></select></div><div className="field"><label>دافع عام — يراه كل اللاعبين</label><textarea className="input song-admin-textarea" maxLength={500} value={role.public_motive} onChange={(event) => updateRole(index, "public_motive", event.target.value)} /></div><div className="field"><label>الكارت السري — يراه صاحب الدور فقط</label><textarea className="input song-admin-textarea" maxLength={1000} value={role.private_card_text} onChange={(event) => updateRole(index, "private_card_text", event.target.value)} /></div></div>)}</div>
      <div className="mafioso-admin-section"><h4>الأدلة الأربعة</h4><p>في كل جولة يظهر دليل واحد ثم يبدأ نقاش 5 دقائق وتصويت واحد.</p>{clues.map((clue, index) => <div className="field" key={index}><label>الدليل {index + 1}</label><textarea className="input song-admin-textarea" maxLength={500} value={clue.clue_text} onChange={(event) => updateClue(index, event.target.value)} /></div>)}</div>
      <div className="mafioso-admin-section"><h4>المشهد الأخير</h4><div className="field"><label>عنوان كشف الحقيقة</label><input className="input" value={revealTitle} maxLength={120} onChange={(event) => setRevealTitle(event.target.value)} /></div><div className="field"><label>القصة الحقيقية التي تظهر في النهاية</label><textarea className="input song-admin-textarea" maxLength={3500} value={revealStory} onChange={(event) => setRevealStory(event.target.value)} /></div><div className="field"><label>فويس أوفر النهاية (اختياري، حتى 5MB)</label><input key={fileKey} className="input" type="file" accept="audio/mpeg,audio/mp4,audio/wav,audio/x-wav,audio/ogg" onChange={(event) => { setRevealAudio(event.target.files?.[0] || null); setRemoveReveal(false); }} /><small className="muted">MP3 أو M4A أو WAV أو OGG. يشتغل للكل بعد انتهاء القضية.</small></div>{editingId && <label className="mafioso-admin-remove"><input type="checkbox" checked={removeReveal} disabled={!cases.find((caseRow) => caseRow.id === editingId)?.reveal_audio_path || Boolean(revealAudio)} onChange={(event) => setRemoveReveal(event.target.checked)} /> إزالة الفويس أوفر المحفوظ بدلًا من استبداله</label>}</div>
      <label className="mafioso-admin-active"><input type="checkbox" checked={isActive} onChange={(event) => setIsActive(event.target.checked)} /> القضية مفعّلة وتدخل السحب العشوائي للرومات الجديدة</label>
      <div className="mafioso-admin-actions">{editingId && <button className="btn btn-outline" onClick={resetForm} disabled={busy}>إلغاء التعديل</button>}<ShakeButton className="btn btn-gold" onClick={save} disabled={busy}>{busy ? "جاري الحفظ…" : editingId ? "احفظ تعديل القضية" : "أضف القضية"}</ShakeButton></div>
    </div>
    <h3>القضايا الموجودة ({cases.length})</h3>{loading ? <div className="card empty">جاري تحميل ملفات القضايا…</div> : cases.length === 0 ? <div className="card empty">لسه مفيش قضايا. أضف واحدة من فوق عشان لعبة مافيوسو تقدر تبدأ.</div> : <div className="list">{cases.map((caseRow) => <div className="card card-tight mafioso-admin-list-card" key={caseRow.id}><div className="mafioso-admin-case-head"><div><b>{caseRow.title}</b><small>{caseRow.subtitle || "بدون وصف قصير"}</small></div><span className="badge" style={{ color: caseRow.is_active ? "var(--mint)" : "var(--text-muted)" }}>{caseRow.is_active ? "● مفعّلة" : "○ متوقفة"}</span></div><div className="mafioso-admin-case-meta"><span>{caseRow.roles.length}/5 شخصيات</span><span>{caseRow.roles.filter((role) => role.alignment === "mafia").length}/2 مافيوسو</span><span>{caseRow.clues.length}/4 أدلة</span><span>{caseRow.reveal_audio_path ? "✓ فويس أوفر" : "— بدون فويس أوفر"}</span></div><div style={{ display: "flex", gap: 8, marginTop: 12, flexWrap: "wrap" }}><button className="btn btn-outline" style={{ width: "auto", padding: "8px 14px", fontSize: 13 }} onClick={() => edit(caseRow)} disabled={busy}>✎ تعديل</button><button className="btn btn-danger" style={{ width: "auto", padding: "8px 14px", fontSize: 13 }} onClick={() => void remove(caseRow)} disabled={busy}>حذف</button></div></div>)}</div>}
  </>;
}
